##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/caja-extensions
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - gobject-introspection
    - gtk-doc-tools
    - expect #required for unbuffer
    - gcc
    - git
    - iso-codes
    - libtool
    - libcaja-extension-dev
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libgtk-3-dev
    - libgupnp-1.2-dev
    - libstartup-notification0-dev
    - libxml2-utils
    - make
    - pkg-config

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-empty-view --enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/apps/system-file-manager.png
