##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # cafe B-D: libbaul-extension-dev libctk-3-dev libcafe-desktop-dev cafe-common
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - gla11y
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libdbus-1-dev
    - libdbus-glib-1-dev
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglib2.0-doc
    - libgupnp-1.6-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libtool
    - libx11-dev
    - libxml2-dev
    - libxml2-utils
    - make
    - pkg-config
    - python3-lxml
    - quilt
    - shared-mime-info

before_scripts:
  - ./html-cppcheck
  - ./debrepo-install 'libctk-3-dev gir1.2-ctk-3.0 libctk-3-common libctk-3-0 libcail-3-0 libcail-3-dev'
  - ./install-from-git https://github.com/cafe-desktop/cafe-common master
  - ./install-from-git https://github.com/cafe-desktop/cafe-desktop master
  - ./install-from-git https://github.com/cafe-desktop/baul master

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - ./gen-index -l 20 -i https://github.com/${OWNER_NAME}/cafe-icon-theme/raw/master/cafe/16x16/apps/system-file-manager.png
